export const SITE_CONTENT = {
  es: {
    nav: {
      home: "Inicio",
      masoneria: "Masonería",
      historia: "Historia",
      principios: "Principios",
      noticias: "Actualidad",
      biblioteca: "Biblioteca",
      faq: "Preguntas",
      contacto: "Contacto",
    },
    meta: {
      location: "Castellón de la Plana",
      orientOccident: "Or∴ de Castellón",
      founded: "Levantamiento de Columnas · 5 de marzo de 2022",
      tagline: "Del Caos al Cosmos. Del Oriente al Occidente.",
      email: "logiamigdia@gmail.com",
      obedience: "Respetable Logia Migdia nº 102",
    },
    hero: {
      eyebrow: "Respetable Logia Migdia nº 102",
      title: "Una Logia nace con la voluntad de ser espacio de reflexión, trabajo y comunidad.",
      lead: "La Logia es hermandad, es Luz: paso del Caos al Cosmos. Su simbolismo cosmogónico nos recuerda que la Masonería es universal — orientada del Oriente al Occidente, del Cenit al Nadir.",
      cta1: "Solicitar información",
      cta2: "Conocer la Logia",
      caption: "Castellón · fundada 2015 · Levantamiento de Columnas 2022",
    },
    quote: {
      text: "Todo está por hacer. Y con ilusión, rigor y esperanza, seguimos construyendo juntos.",
      attribution: "Palabras del Venerable Maestro — Levantamiento de Columnas, 5 de marzo de 2022",
    },
    masoneria: {
      eyebrow: "I · Qué es la Masonería",
      title: "Una tradición iniciática de perfeccionamiento personal y colectivo.",
      body: [
        "La Masonería es una organización fraternal e iniciática que busca el perfeccionamiento del ser humano y, a través de él, de la sociedad. Se fundamenta en valores universales —libertad, igualdad, fraternidad, tolerancia— entendidos como pilares para construir un mundo más justo.",
        "Su origen se remonta a los gremios de canteros medievales, que transmitían su oficio mediante símbolos y rituales. Con el tiempo, la tradición operativa se transformó en especulativa: una filosofía humanista que invita a la reflexión, al trabajo interior y al compromiso cívico.",
        "En España, la masonería moderna se estableció en el siglo XVIII, con la fundación en Madrid de la primera logia regular en 1728. Desde entonces ha sido espacio de encuentro para hombres y mujeres libres, unidos por el deseo de aprender, mejorar y aportar.",
      ],
      pillars: [
        { n: "I", t: "Libertad", d: "De pensamiento, de conciencia y de palabra. Condición previa a toda búsqueda honesta." },
        { n: "II", t: "Igualdad", d: "Entre hermanos y hermanas, sin distinción de origen, credo, fortuna o condición." },
        { n: "III", t: "Fraternidad", d: "Vínculo activo — no sólo sentimiento — entre quienes comparten la Obra." },
      ],
    },
    historia: {
      eyebrow: "II · Historia",
      title: "Del Triángulo Castàlia al Taller de Migdia.",
      timeline: [
        { year: "2007", t: "Triángulo Castàlia", d: "Nace en Castellón el germen que conducirá, años después, al taller actual. Una pequeña comunidad de buscadores empieza a reunirse bajo los principios de la Orden." },
        { year: "2015", t: "Fundación del taller", d: "Se constituye formalmente la Logia Migdia, continuando el trabajo iniciado por el Triángulo. Migdia — Mediodía — remite al conocimiento, al trabajo y a la cultura del Sur." },
        { year: "2022", t: "Levantamiento de Columnas", d: "El 5 de marzo de 2022 se celebra solemnemente el Levantamiento de Columnas de la Respetable Logia Migdia nº 102, reconociendo el camino recorrido y los hermanos que lo hicieron posible." },
        { year: "Hoy", t: "Taller en actividad", d: "La Logia continúa su labor con rigor y esperanza. Se reivindican la filantropía, la humildad, la tolerancia y la justicia, rechazando imposiciones e individualismos." },
      ],
    },
    principios: {
      eyebrow: "III · Principios",
      title: "Libertad, Igualdad, Fraternidad.",
      sub: "No eslogan, sino método. Tres palabras que ordenan el trabajo masónico y señalan el sentido de la Obra.",
    },
    noticias: {
      eyebrow: "IV · Actualidad",
      title: "Tenidas blancas y actos públicos.",
      sub: "La Logia celebra periódicamente tenidas abiertas al público profano — conferencias, coloquios, actos conmemorativos — donde exponemos nuestro trabajo y abrimos conversación con la ciudad.",
      items: [
        { date: "12 MAY 2026", tag: "Tenida Blanca", t: "La Masonería y la Ilustración valenciana", d: "Conferencia pública sobre la influencia masónica en los movimientos ilustrados del siglo XVIII en el Reino de Valencia. Abierta a todo público.", place: "Castellón · 19:30 h" },
        { date: "21 JUN 2026", tag: "Solsticio", t: "Tenida de San Juan de Verano", d: "Celebración del solsticio de verano, una de las dos grandes fechas del calendario masónico. Reservada a miembros y hermanos visitantes.", place: "Taller · 20:00 h" },
        { date: "18 SEP 2026", tag: "Coloquio", t: "Tolerancia y laicidad en el siglo XXI", d: "Mesa redonda pública con invitados del ámbito académico y filosófico sobre el papel de la laicidad en la sociedad contemporánea.", place: "Castellón · 19:00 h" },
      ],
      cta: "Ver calendario completo",
    },
    biblioteca: {
      eyebrow: "V · Biblioteca",
      title: "Lecturas y recursos.",
      sub: "Selección de textos abiertos al profano interesado. Obras introductorias, documentos históricos y reflexiones contemporáneas sobre la tradición masónica.",
      items: [
        { cat: "Introducción", t: "¿Qué es la Masonería?", author: "AA.VV.", pages: "64 pp." },
        { cat: "Historia", t: "La Masonería en España — s. XVIII–XX", author: "J. A. Ferrer Benimeli", pages: "342 pp." },
        { cat: "Simbolismo", t: "El simbolismo del Templo", author: "Jules Boucher", pages: "288 pp." },
        { cat: "Filosofía", t: "Humanismo y tradición iniciática", author: "AA.VV.", pages: "128 pp." },
        { cat: "Documento", t: "Constituciones de Anderson (1723)", author: "James Anderson", pages: "96 pp." },
        { cat: "Ensayo", t: "La Logia y la ciudad", author: "Migdia nº 102", pages: "24 pp." },
      ],
    },
    faq: {
      eyebrow: "VI · Preguntas frecuentes",
      title: "Las dudas más habituales de quien se acerca por primera vez.",
      items: [
        { q: "¿La Masonería es una religión?", a: "No. La Masonería no es una religión ni la sustituye. Exige de sus miembros el respeto por la libertad de conciencia y la creencia en un principio superior, pero no impone ningún dogma ni sistema de culto." },
        { q: "¿Es una sociedad secreta?", a: "No. Es una sociedad discreta: sus principios, su historia y su funcionamiento son públicos, como atestigua este mismo sitio. Lo que se reserva es la identidad de los miembros y el contenido simbólico de los trabajos, por respeto al método iniciático." },
        { q: "¿Admite mujeres?", a: "Sí. La Masonería contemporánea es mixta en muchas de sus obediencias, incluida la nuestra. Hombres y mujeres libres trabajan juntos sobre los mismos principios." },
        { q: "¿Qué se requiere para ingresar?", a: "Ser mayor de edad, libre y de buenas costumbres. Tener voluntad sincera de trabajar sobre uno mismo. El proceso incluye una entrevista personal y, posteriormente, una solicitud formal al taller." },
        { q: "¿Hay que pagar?", a: "La Logia se sostiene con las aportaciones de sus miembros. No se busca lucro. Las cuotas cubren el mantenimiento del taller, la obediencia y las actividades colectivas." },
        { q: "¿Qué ocupa el tiempo de una tenida?", a: "Las tenidas combinan ritual, estudio y debate fraternal. En ellas se leen planchas (trabajos escritos), se discuten temas filosóficos, éticos o simbólicos, y se practican ceremonias tradicionales." },
      ],
    },
    contacto: {
      eyebrow: "VII · Contacto",
      title: "Si quieres saber más, escríbenos.",
      sub: "Respondemos personalmente a cada mensaje. La discreción es condición de nuestro trabajo; los datos que compartas sólo serán vistos por los hermanos responsables de la correspondencia.",
      fields: { name: "Nombre", email: "Correo electrónico", subject: "Asunto", message: "Mensaje" },
      subjects: ["Solicitud de información", "Asistir a una tenida blanca", "Biblioteca y recursos", "Prensa / medios", "Otros"],
      send: "Enviar mensaje",
      note: "También puedes escribirnos directamente a",
    },
    footer: {
      legend: "Respetable Logia Migdia nº 102 — Or∴ de Castellón",
      tagline: "Construimos juntos. Del Caos al Cosmos.",
      legal: ["Aviso legal", "Privacidad", "Cookies"],
    },
  },
  ca: {
    nav: {
      home: "Inici",
      masoneria: "Maçoneria",
      historia: "Història",
      principios: "Principis",
      noticias: "Actualitat",
      biblioteca: "Biblioteca",
      faq: "Preguntes",
      contacto: "Contacte",
    },
    meta: {
      location: "Castelló de la Plana",
      orientOccident: "Or∴ de Castelló",
      founded: "Aixecament de Columnes · 5 de març de 2022",
      tagline: "Del Caos al Cosmos. De l'Orient a l'Occident.",
      email: "logiamigdia@gmail.com",
      obedience: "Respectable Lògia Migdia núm. 102",
    },
    hero: {
      eyebrow: "Respectable Lògia Migdia núm. 102",
      title: "Una Lògia neix amb la voluntat de ser espai de reflexió, treball i comunitat.",
      lead: "La Lògia és germanor, és Llum: pas del Caos al Cosmos. El seu simbolisme cosmogònic ens recorda que la Maçoneria és universal — orientada de l'Orient a l'Occident, del Zenit al Nadir.",
      cta1: "Sol·licitar informació",
      cta2: "Conèixer la Lògia",
      caption: "Castelló · fundada 2015 · Aixecament de Columnes 2022",
    },
    quote: {
      text: "Tot està per fer. I amb il·lusió, rigor i esperança, continuem construint junts.",
      attribution: "Paraules del Venerable Mestre — Aixecament de Columnes, 5 de març de 2022",
    },
    masoneria: {
      eyebrow: "I · Què és la Maçoneria",
      title: "Una tradició iniciàtica de perfeccionament personal i col·lectiu.",
      body: [
        "La Maçoneria és una organització fraternal i iniciàtica que cerca el perfeccionament de l'ésser humà i, a través d'ell, de la societat. Es fonamenta en valors universals —llibertat, igualtat, fraternitat, tolerància— entesos com a pilars per construir un món més just.",
        "El seu origen es remunta als gremis de picapedrers medievals, que transmetien el seu ofici mitjançant símbols i rituals. Amb el temps, la tradició operativa es transformà en especulativa: una filosofia humanista que convida a la reflexió, al treball interior i al compromís cívic.",
        "A Espanya, la maçoneria moderna s'establí al segle XVIII, amb la fundació a Madrid de la primera lògia regular el 1728. Des d'aleshores ha estat espai de trobada per a homes i dones lliures, units pel desig d'aprendre, millorar i aportar.",
      ],
      pillars: [
        { n: "I", t: "Llibertat", d: "De pensament, de consciència i de paraula. Condició prèvia a tota cerca honesta." },
        { n: "II", t: "Igualtat", d: "Entre germans i germanes, sense distinció d'origen, credo, fortuna o condició." },
        { n: "III", t: "Fraternitat", d: "Vincle actiu — no només sentiment — entre els qui comparteixen l'Obra." },
      ],
    },
    historia: {
      eyebrow: "II · Història",
      title: "Del Triangle Castàlia al Taller de Migdia.",
      timeline: [
        { year: "2007", t: "Triangle Castàlia", d: "Neix a Castelló el germen que conduirà, anys després, al taller actual. Una petita comunitat de cercadors comença a reunir-se sota els principis de l'Orde." },
        { year: "2015", t: "Fundació del taller", d: "Es constitueix formalment la Lògia Migdia, continuant el treball iniciat pel Triangle. Migdia remet al coneixement, al treball i a la cultura del Sud." },
        { year: "2022", t: "Aixecament de Columnes", d: "El 5 de març de 2022 se celebra solemnement l'Aixecament de Columnes de la Respectable Lògia Migdia núm. 102, reconeixent el camí recorregut i els germans que el van fer possible." },
        { year: "Avui", t: "Taller en activitat", d: "La Lògia continua la seva tasca amb rigor i esperança. Es reivindiquen la filantropia, la humilitat, la tolerància i la justícia, rebutjant imposicions i individualismes." },
      ],
    },
    principios: {
      eyebrow: "III · Principis",
      title: "Llibertat, Igualtat, Fraternitat.",
      sub: "No pas un eslògan, sinó un mètode. Tres paraules que ordenen el treball maçònic i assenyalen el sentit de l'Obra.",
    },
    noticias: {
      eyebrow: "IV · Actualitat",
      title: "Tingudes blanques i actes públics.",
      sub: "La Lògia celebra periòdicament tingudes obertes al públic profà — conferències, col·loquis, actes commemoratius — on exposem el nostre treball i obrim conversa amb la ciutat.",
      items: [
        { date: "12 MAIG 2026", tag: "Tinguda Blanca", t: "La Maçoneria i la Il·lustració valenciana", d: "Conferència pública sobre la influència maçònica en els moviments il·lustrats del segle XVIII al Regne de València. Oberta a tot el públic.", place: "Castelló · 19:30 h" },
        { date: "21 JUN 2026", tag: "Solstici", t: "Tinguda de Sant Joan d'Estiu", d: "Celebració del solstici d'estiu, una de les dues grans dates del calendari maçònic. Reservada a membres i germans visitants.", place: "Taller · 20:00 h" },
        { date: "18 SET 2026", tag: "Col·loqui", t: "Tolerància i laïcitat al segle XXI", d: "Taula rodona pública amb convidats de l'àmbit acadèmic i filosòfic sobre el paper de la laïcitat a la societat contemporània.", place: "Castelló · 19:00 h" },
      ],
      cta: "Veure calendari complet",
    },
    biblioteca: {
      eyebrow: "V · Biblioteca",
      title: "Lectures i recursos.",
      sub: "Selecció de textos oberts al profà interessat. Obres introductòries, documents històrics i reflexions contemporànies sobre la tradició maçònica.",
      items: [
        { cat: "Introducció", t: "Què és la Maçoneria?", author: "AA.DD.", pages: "64 pp." },
        { cat: "Història", t: "La Maçoneria a Espanya — s. XVIII–XX", author: "J. A. Ferrer Benimeli", pages: "342 pp." },
        { cat: "Simbolisme", t: "El simbolisme del Temple", author: "Jules Boucher", pages: "288 pp." },
        { cat: "Filosofia", t: "Humanisme i tradició iniciàtica", author: "AA.DD.", pages: "128 pp." },
        { cat: "Document", t: "Constitucions d'Anderson (1723)", author: "James Anderson", pages: "96 pp." },
        { cat: "Assaig", t: "La Lògia i la ciutat", author: "Migdia núm. 102", pages: "24 pp." },
      ],
    },
    faq: {
      eyebrow: "VI · Preguntes freqüents",
      title: "Els dubtes més habituals de qui s'acosta per primera vegada.",
      items: [
        { q: "La Maçoneria és una religió?", a: "No. La Maçoneria no és una religió ni la substitueix. Exigeix dels seus membres el respecte per la llibertat de consciència i la creença en un principi superior, però no imposa cap dogma ni sistema de culte." },
        { q: "És una societat secreta?", a: "No. És una societat discreta: els seus principis, la seva història i el seu funcionament són públics, com testifica aquest mateix lloc. El que es reserva és la identitat dels membres i el contingut simbòlic dels treballs, per respecte al mètode iniciàtic." },
        { q: "Admet dones?", a: "Sí. La Maçoneria contemporània és mixta en moltes de les seves obediències, inclosa la nostra. Homes i dones lliures treballen junts sobre els mateixos principis." },
        { q: "Què es requereix per ingressar?", a: "Ser major d'edat, lliure i de bons costums. Tenir voluntat sincera de treballar sobre un mateix. El procés inclou una entrevista personal i, posteriorment, una sol·licitud formal al taller." },
        { q: "S'ha de pagar?", a: "La Lògia se sosté amb les aportacions dels seus membres. No es cerca lucre. Les quotes cobreixen el manteniment del taller, l'obediència i les activitats col·lectives." },
        { q: "Què ocupa el temps d'una tinguda?", a: "Les tingudes combinen ritual, estudi i debat fraternal. S'hi llegeixen planxes (treballs escrits), es discuteixen temes filosòfics, ètics o simbòlics, i es practiquen cerimònies tradicionals." },
      ],
    },
    contacto: {
      eyebrow: "VII · Contacte",
      title: "Si vols saber-ne més, escriu-nos.",
      sub: "Responem personalment a cada missatge. La discreció és condició del nostre treball; les dades que comparteixis només seran vistes pels germans responsables de la correspondència.",
      fields: { name: "Nom", email: "Correu electrònic", subject: "Assumpte", message: "Missatge" },
      subjects: ["Sol·licitud d'informació", "Assistir a una tinguda blanca", "Biblioteca i recursos", "Premsa / mitjans", "Altres"],
      send: "Enviar missatge",
      note: "També pots escriure'ns directament a",
    },
    footer: {
      legend: "Respectable Lògia Migdia núm. 102 — Or∴ de Castelló",
      tagline: "Construïm junts. Del Caos al Cosmos.",
      legal: ["Avís legal", "Privacitat", "Galetes"],
    },
  },
}
